#default
vm:
  user:
    session:
      lifetime: 60000 #秒
  src:
    img:
      url: /src/img/
      default: default.png
      path: d:/vm/src/img
      maxSize: 2097152
      allowSuffixs: jpg,png
    video:
      url: /src/video/
      default: default.mp4
      path: d:/vm/src/video
server:
  port: ${random.int(8000,9000)}

# profiles

---
spring:
  profiles: dev
server:
  port: ${random.int(8000,9000)}
vm:
  src:
    img:
      path: d:/vm/src/img
    video:
      path: d:/vm/src/video



---
spring:
  profiles: prod
server:
  port: ${random.int(8000,9000)}
vm:
  src:
    img:
      path: /usr/local/src/vm/src/img/
    video:
      path: /usr/local/src/vm/src/video/
