spring:
  #db connection
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.191.94:3306/vm?useUnicode=true&amp;characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull&amp;allowMultiQueries=true&amp;autoReconnect=true
    username: root
    password: 123

#spring.cloud.config.uri= http://localhost:8888/
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01:1111/eureka/,http://eureka02:1112/eureka/

---
spring:
  profiles: providerMovie01
server:
  port: 3331
---
spring:
  profiles: providerMovie02
server:
  port: 3332
