server:
  port: 1111
spring:
  application:
    name: EurekaServer
eureka:
  instance:
    hostname: eureka01
  client:
    service-url:
      defaultZone:
        http://eureka01:1111/eureka/,http://eureka02:1112/eureka/