#禁用eureka注册自己
eureka:
  client:
    fetch:
      registry: false
    register-with-eureka: false
#eureka集群名
spring:
  application:
    name: eureka-cluster
#通过spring.profiles.active=[eureka01|eureka02]激活
--- #eureka01
spring:
  profiles: eureka01
server:
  port: 1111
eureka:
  instance:
    hostname: eureka01
  client:
    service-url:
      default-zone: http://eureka02:1112/eureka
security:
  basic:
    enabled: true
  user:
    name: godaner
    password: ZK19951217.

--- #eureka02
spring:
  profiles: eureka02
server:
  port: 1112
eureka:
  instance:
    hostname: eureka02
  client:
    service-url:
      default-zone: http://eureka01:1111/eureka
security:
  basic:
    enabled: true
  user:
    name: godaner
    password: ZK19951217.