spring:
  application:
    name: eureka-cluster
---
spring:
  profiles: eureka01
server:
  port: 1111
eureka:
  instance:
    hostname: eureka01
  client:
    service-url:
      default-zone: http://eureka02:1112/eureka

---
spring:
  profiles: eureka02
server:
  port: 1112
eureka:
  instance:
    hostname: eureka02
  client:
    service-url:
      default-zone: http://eureka01:1111/eureka